### ISSUE TITLE
Coloring would be great

### ISSUE THREAD

**Issue by BluetriX** [six-two/mkdocs-placeholder-plugin#2]
Hello,

this is a very cool project! I saw something similar in the Google documentation some time ago (example: https://cloud.google.com/sql/docs/postgres/import-export/import-export-dmp ) and looked for a similar solution for MkDocs but found nothing.

I think that plugin is very useful but I have one more wish. Would it be possible to make the replaced parts visually recognizable? So similar to the Google-doc? Because then you would see in code blocks directly which place comes from the variables and which is static.

Greetings from Germany

Erik

**Comment by six-two** [comment]
Hi Erik,

I think it would be pretty easy to tag all replaced values, so that you could apply custom styling to it. In fact I was planing on wrapping replaced values in something like the following, so that I could update placeholder values without reloading the page:

```html
<span class="placeholder-value" data-placeholder="PLACEHOLDER_NAME">PLACEHOLDER_VALUE</span>
```

That should make it easy to style them. The question would be, how to properly handle nested placeholders. Imagine something like this:
```yaml
URL:
    default: xPROTOx://xHOSTNAMEx/xPATHx
    read_only: true
```

Should the inner placeholders be highlighted, or would it be enough to just highlight the outer placeholder?

I am currently in the process of rewriting the entire JavaScript code, so it may take up to a couple weeks to have the master branch back in a state, where I can add the feature. After that I will try to implement it. If you want something sooner, you could locally modify the `on_page_content` method in [plugin.py](https://github.com/six-two/mkdocs-placeholder-plugin/blob/main/src/mkdocs_placeholder_plugin/plugin.py#L63). If it would replace any occurrence of `xYOUR_PLACEHOLDER_NAMEx` with something like `<span class="placeholder-value" "> xYOUR_PLACEHOLDER_NAMEx</span>`, you should have a version, where you could experiment with styling :)

Greetings from a fellow German,
six-two

**Comment by BluetriX** [comment]
That sounds great. Thanks also for the "workaround". I will test this one.

For me it would fit if only the outer part or the whole part is highlighted (nested placeholder).

**Comment by six-two** [comment]
It seems to pretty much work as I expected. I have added some highlighting (grey rounded background), when the `debug_javascript` plugin option is set to `true` (it's useful when debugging). You can see it [on the dev version of the documentation](https://dev.mkdocs-placeholder-plugin.six-two.dev/demo/). It's not pretty, but proves that it can be done.

When you set `debug_javascript` to `false`, you can add your own CSS styling like this:
```css
.placeholder-value {
    background-color: yellow;
}
```

Is this close to what you were looking for?

There are still a bunch of bugs on the `main` branch, so a release may still be a bit of.

**Comment by six-two** [comment]
Version 0.3.0 has just been released and includes this feature. I also added a short bit of documentation on how to do the highlighting on the [Advanced usage page](https://mkdocs-placeholder-plugin.six-two.dev/advanced-usage/#highlighting-placeholders)
