### ISSUE TITLE
Setting to update placeholders on leaving the input tag

### ISSUE THREAD

**Issue by phiranf** [six-two/mkdocs-placeholder-plugin#4]
Thank you for your plugin!

It would be great if there was an option to update all placeholders upon leaving/loosing focus of its corresponding input tag instead of having to confirm it with enter each time.

Maybe just call the `PlaceholderPlugin.reload_page` function (when it's fixed ;) ) whenever the input tag isn't in focus anymore?

**Comment by six-two** [comment]
Hi and thank you for the suggestion!

I will look into it after my holidays (next 2 weeks). One complication that I see is that users may have accidentally edited or partially deleted a long/complex value (for example a randomly generated password that they need) and want to restore the original. For that case there may need to be a key binding to abort/revert the current edit.

If it becomes an optional configuration (instead of the new default) there may also be a need to tell the user when values are saved/applied (“Do I need to press enter?”). Otherwise they would be confused if the site owner changes the configuration or they visit multiple sites with different configs.

**Comment by six-two** [comment]
I implemented something like you suggested and it is really useful and way more intuitive. You can try it out on the dev branch's docs: https://dev.mkdocs-placeholder-plugin.six-two.dev/demo/

It may take a couple weeks to ship this feature, since I want to finish the rewrite of the python code for the next release.

**Comment by six-two** [comment]
The feature was released in version 0.4.0. It is enabled by default, but can be disabled using the [apply_change_on_focus_change](https://mkdocs-placeholder-plugin.six-two.dev/configuration/#apply_change_on_focus_change) setting. It can also be en/disabled by users using the `Apply value when focus changes away*` checkbox in the settings.

**Comment by phiranf** [comment]
Thank you very much, I’ve tried it out on the demo page and it works like a charm!
